# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parameter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fparameter.proto\x12\tparameter\x1a\x1cgoogle/protobuf/struct.proto\"\xb1\x01\n\tParameter\x12\x14\n\x0cparameter_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12%\n\x05value\x18\x05 \x01(\x0b\x32\x16.google.protobuf.Value\x12\'\n\x07options\x18\x06 \x03(\x0b\x32\x16.google.protobuf.Value\x12\r\n\x05range\x18\x07 \x03(\x01\x62\x06proto3')



_PARAMETER = DESCRIPTOR.message_types_by_name['Parameter']
Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETER,
  '__module__' : 'parameter_pb2'
  # @@protoc_insertion_point(class_scope:parameter.Parameter)
  })
_sym_db.RegisterMessage(Parameter)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PARAMETER._serialized_start=61
  _PARAMETER._serialized_end=238
# @@protoc_insertion_point(module_scope)
