# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipelines.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpipelines.proto\x12\tpipelines\x1a\x1cgoogle/protobuf/struct.proto\".\n\x13GetPipelinesRequest\x12\x17\n\x0fwith_parameters\x18\x01 \x01(\x08\"U\n\x05Value\x12\x16\n\x0cnumber_value\x18\x01 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x02 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x03 \x01(\x08H\x00\x42\x06\n\x04kind\"\x98\x01\n\x11PipelineParameter\x12\x14\n\x0cparameter_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x1f\n\x05value\x18\x04 \x01(\x0b\x32\x10.pipelines.Value\x12!\n\x07options\x18\x05 \x03(\x0b\x32\x10.pipelines.Value\x12\r\n\x05range\x18\x06 \x03(\x01\"\xad\x01\n\x08Pipeline\x12\x13\n\x0bpipeline_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x30\n\nparameters\x18\x05 \x03(\x0b\x32\x1c.pipelines.PipelineParameter\x12)\n\x08metadata\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct\"B\n\x12GetPipelineRequest\x12\x13\n\x0bpipeline_id\x18\x01 \x01(\t\x12\x17\n\x0fwith_parameters\x18\x02 \x01(\x08\x32\x95\x01\n\tPipelines\x12\x45\n\x0cGetPipelines\x12\x1e.pipelines.GetPipelinesRequest\x1a\x13.pipelines.Pipeline0\x01\x12\x41\n\x0bGetPipeline\x12\x1d.pipelines.GetPipelineRequest\x1a\x13.pipelines.Pipelineb\x06proto3')



_GETPIPELINESREQUEST = DESCRIPTOR.message_types_by_name['GetPipelinesRequest']
_VALUE = DESCRIPTOR.message_types_by_name['Value']
_PIPELINEPARAMETER = DESCRIPTOR.message_types_by_name['PipelineParameter']
_PIPELINE = DESCRIPTOR.message_types_by_name['Pipeline']
_GETPIPELINEREQUEST = DESCRIPTOR.message_types_by_name['GetPipelineRequest']
GetPipelinesRequest = _reflection.GeneratedProtocolMessageType('GetPipelinesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPIPELINESREQUEST,
  '__module__' : 'pipelines_pb2'
  # @@protoc_insertion_point(class_scope:pipelines.GetPipelinesRequest)
  })
_sym_db.RegisterMessage(GetPipelinesRequest)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
  'DESCRIPTOR' : _VALUE,
  '__module__' : 'pipelines_pb2'
  # @@protoc_insertion_point(class_scope:pipelines.Value)
  })
_sym_db.RegisterMessage(Value)

PipelineParameter = _reflection.GeneratedProtocolMessageType('PipelineParameter', (_message.Message,), {
  'DESCRIPTOR' : _PIPELINEPARAMETER,
  '__module__' : 'pipelines_pb2'
  # @@protoc_insertion_point(class_scope:pipelines.PipelineParameter)
  })
_sym_db.RegisterMessage(PipelineParameter)

Pipeline = _reflection.GeneratedProtocolMessageType('Pipeline', (_message.Message,), {
  'DESCRIPTOR' : _PIPELINE,
  '__module__' : 'pipelines_pb2'
  # @@protoc_insertion_point(class_scope:pipelines.Pipeline)
  })
_sym_db.RegisterMessage(Pipeline)

GetPipelineRequest = _reflection.GeneratedProtocolMessageType('GetPipelineRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPIPELINEREQUEST,
  '__module__' : 'pipelines_pb2'
  # @@protoc_insertion_point(class_scope:pipelines.GetPipelineRequest)
  })
_sym_db.RegisterMessage(GetPipelineRequest)

_PIPELINES = DESCRIPTOR.services_by_name['Pipelines']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETPIPELINESREQUEST._serialized_start=60
  _GETPIPELINESREQUEST._serialized_end=106
  _VALUE._serialized_start=108
  _VALUE._serialized_end=193
  _PIPELINEPARAMETER._serialized_start=196
  _PIPELINEPARAMETER._serialized_end=348
  _PIPELINE._serialized_start=351
  _PIPELINE._serialized_end=524
  _GETPIPELINEREQUEST._serialized_start=526
  _GETPIPELINEREQUEST._serialized_end=592
  _PIPELINES._serialized_start=595
  _PIPELINES._serialized_end=744
# @@protoc_insertion_point(module_scope)
