# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reader.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import parameter_pb2 as parameter__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creader.proto\x12\x06reader\x1a\x0fparameter.proto\"N\n\x0fReaderComponent\x12\x11\n\treader_id\x18\x01 \x01(\t\x12(\n\nparameters\x18\x02 \x03(\x0b\x32\x14.parameter.Parameter\"\x13\n\x11GetReadersRequest\">\n\x12GetReadersResponse\x12(\n\x07readers\x18\x01 \x03(\x0b\x32\x17.reader.ReaderComponent\"q\n\x11GetAnswersRequest\x12\'\n\x06reader\x18\x01 \x01(\x0b\x32\x17.reader.ReaderComponent\x12\x0f\n\x07queries\x18\x02 \x03(\t\x12\"\n\x08\x63ontexts\x18\x03 \x03(\x0b\x32\x10.reader.Contexts\"\x19\n\x08\x43ontexts\x12\r\n\x05texts\x18\x01 \x03(\t\"{\n\x06\x41nswer\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x19\n\x11start_char_offset\x18\x02 \x01(\r\x12\x17\n\x0f\x65nd_char_offset\x18\x03 \x01(\r\x12\x18\n\x10\x63onfidence_score\x18\x04 \x01(\x01\x12\x15\n\rcontext_index\x18\x05 \x01(\r\"4\n\x11\x41nswersForContext\x12\x1f\n\x07\x61nswers\x18\x01 \x03(\x0b\x32\x0e.reader.Answer\"E\n\x0f\x41nswersForQuery\x12\x32\n\x0f\x63ontext_answers\x18\x01 \x03(\x0b\x32\x19.reader.AnswersForContext\"D\n\x12GetAnswersResponse\x12.\n\rquery_answers\x18\x01 \x03(\x0b\x32\x17.reader.AnswersForQuery2\x92\x01\n\x06Reader\x12\x43\n\nGetReaders\x12\x19.reader.GetReadersRequest\x1a\x1a.reader.GetReadersResponse\x12\x43\n\nGetAnswers\x12\x19.reader.GetAnswersRequest\x1a\x1a.reader.GetAnswersResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reader_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _READERCOMPONENT._serialized_start=41
  _READERCOMPONENT._serialized_end=119
  _GETREADERSREQUEST._serialized_start=121
  _GETREADERSREQUEST._serialized_end=140
  _GETREADERSRESPONSE._serialized_start=142
  _GETREADERSRESPONSE._serialized_end=204
  _GETANSWERSREQUEST._serialized_start=206
  _GETANSWERSREQUEST._serialized_end=319
  _CONTEXTS._serialized_start=321
  _CONTEXTS._serialized_end=346
  _ANSWER._serialized_start=348
  _ANSWER._serialized_end=471
  _ANSWERSFORCONTEXT._serialized_start=473
  _ANSWERSFORCONTEXT._serialized_end=525
  _ANSWERSFORQUERY._serialized_start=527
  _ANSWERSFORQUERY._serialized_end=596
  _GETANSWERSRESPONSE._serialized_start=598
  _GETANSWERSRESPONSE._serialized_end=666
  _READER._serialized_start=669
  _READER._serialized_end=815
# @@protoc_insertion_point(module_scope)
