# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reader.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import parameter_pb2 as parameter__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creader.proto\x12\x06reader\x1a\x0fparameter.proto\"E\n\x06Reader\x12\x11\n\treader_id\x18\x01 \x01(\t\x12(\n\nparameters\x18\x02 \x03(\x0b\x32\x14.parameter.Parameter\"\x13\n\x11GetReadersRequest\"5\n\x12GetReadersResponse\x12\x1f\n\x07readers\x18\x01 \x03(\x0b\x32\x0e.reader.Reader\"h\n\x11GetAnswersRequest\x12\x1e\n\x06reader\x18\x01 \x01(\x0b\x32\x0e.reader.Reader\x12\x0f\n\x07queries\x18\x02 \x03(\t\x12\"\n\x08\x63ontexts\x18\x03 \x03(\x0b\x32\x10.reader.Contexts\"\x19\n\x08\x43ontexts\x12\r\n\x05texts\x18\x01 \x03(\t\"$\n\x06Offset\x12\r\n\x05start\x18\x01 \x01(\r\x12\x0b\n\x03\x65nd\x18\x02 \x01(\r\"u\n\x08\x45vidence\x12\x1a\n\rcontext_index\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04text\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1f\n\x07offsets\x18\x03 \x03(\x0b\x32\x0e.reader.OffsetB\x10\n\x0e_context_indexB\x07\n\x05_text\"U\n\x06\x41nswer\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x02 \x01(\x01\x12#\n\tevidences\x18\x03 \x03(\x0b\x32\x10.reader.Evidence\"4\n\x11\x41nswersForContext\x12\x1f\n\x07\x61nswers\x18\x01 \x03(\x0b\x32\x0e.reader.Answer\"E\n\x0f\x41nswersForQuery\x12\x32\n\x0f\x63ontext_answers\x18\x01 \x03(\x0b\x32\x19.reader.AnswersForContext\"D\n\x12GetAnswersResponse\x12.\n\rquery_answers\x18\x01 \x03(\x0b\x32\x17.reader.AnswersForQuery2\x9a\x01\n\x0eReadingService\x12\x43\n\nGetReaders\x12\x19.reader.GetReadersRequest\x1a\x1a.reader.GetReadersResponse\x12\x43\n\nGetAnswers\x12\x19.reader.GetAnswersRequest\x1a\x1a.reader.GetAnswersResponseb\x06proto3')



_READER = DESCRIPTOR.message_types_by_name['Reader']
_GETREADERSREQUEST = DESCRIPTOR.message_types_by_name['GetReadersRequest']
_GETREADERSRESPONSE = DESCRIPTOR.message_types_by_name['GetReadersResponse']
_GETANSWERSREQUEST = DESCRIPTOR.message_types_by_name['GetAnswersRequest']
_CONTEXTS = DESCRIPTOR.message_types_by_name['Contexts']
_OFFSET = DESCRIPTOR.message_types_by_name['Offset']
_EVIDENCE = DESCRIPTOR.message_types_by_name['Evidence']
_ANSWER = DESCRIPTOR.message_types_by_name['Answer']
_ANSWERSFORCONTEXT = DESCRIPTOR.message_types_by_name['AnswersForContext']
_ANSWERSFORQUERY = DESCRIPTOR.message_types_by_name['AnswersForQuery']
_GETANSWERSRESPONSE = DESCRIPTOR.message_types_by_name['GetAnswersResponse']
Reader = _reflection.GeneratedProtocolMessageType('Reader', (_message.Message,), {
  'DESCRIPTOR' : _READER,
  '__module__' : 'reader_pb2'
  # @@protoc_insertion_point(class_scope:reader.Reader)
  })
_sym_db.RegisterMessage(Reader)

GetReadersRequest = _reflection.GeneratedProtocolMessageType('GetReadersRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREADERSREQUEST,
  '__module__' : 'reader_pb2'
  # @@protoc_insertion_point(class_scope:reader.GetReadersRequest)
  })
_sym_db.RegisterMessage(GetReadersRequest)

GetReadersResponse = _reflection.GeneratedProtocolMessageType('GetReadersResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETREADERSRESPONSE,
  '__module__' : 'reader_pb2'
  # @@protoc_insertion_point(class_scope:reader.GetReadersResponse)
  })
_sym_db.RegisterMessage(GetReadersResponse)

GetAnswersRequest = _reflection.GeneratedProtocolMessageType('GetAnswersRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETANSWERSREQUEST,
  '__module__' : 'reader_pb2'
  # @@protoc_insertion_point(class_scope:reader.GetAnswersRequest)
  })
_sym_db.RegisterMessage(GetAnswersRequest)

Contexts = _reflection.GeneratedProtocolMessageType('Contexts', (_message.Message,), {
  'DESCRIPTOR' : _CONTEXTS,
  '__module__' : 'reader_pb2'
  # @@protoc_insertion_point(class_scope:reader.Contexts)
  })
_sym_db.RegisterMessage(Contexts)

Offset = _reflection.GeneratedProtocolMessageType('Offset', (_message.Message,), {
  'DESCRIPTOR' : _OFFSET,
  '__module__' : 'reader_pb2'
  # @@protoc_insertion_point(class_scope:reader.Offset)
  })
_sym_db.RegisterMessage(Offset)

Evidence = _reflection.GeneratedProtocolMessageType('Evidence', (_message.Message,), {
  'DESCRIPTOR' : _EVIDENCE,
  '__module__' : 'reader_pb2'
  # @@protoc_insertion_point(class_scope:reader.Evidence)
  })
_sym_db.RegisterMessage(Evidence)

Answer = _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), {
  'DESCRIPTOR' : _ANSWER,
  '__module__' : 'reader_pb2'
  # @@protoc_insertion_point(class_scope:reader.Answer)
  })
_sym_db.RegisterMessage(Answer)

AnswersForContext = _reflection.GeneratedProtocolMessageType('AnswersForContext', (_message.Message,), {
  'DESCRIPTOR' : _ANSWERSFORCONTEXT,
  '__module__' : 'reader_pb2'
  # @@protoc_insertion_point(class_scope:reader.AnswersForContext)
  })
_sym_db.RegisterMessage(AnswersForContext)

AnswersForQuery = _reflection.GeneratedProtocolMessageType('AnswersForQuery', (_message.Message,), {
  'DESCRIPTOR' : _ANSWERSFORQUERY,
  '__module__' : 'reader_pb2'
  # @@protoc_insertion_point(class_scope:reader.AnswersForQuery)
  })
_sym_db.RegisterMessage(AnswersForQuery)

GetAnswersResponse = _reflection.GeneratedProtocolMessageType('GetAnswersResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETANSWERSRESPONSE,
  '__module__' : 'reader_pb2'
  # @@protoc_insertion_point(class_scope:reader.GetAnswersResponse)
  })
_sym_db.RegisterMessage(GetAnswersResponse)

_READINGSERVICE = DESCRIPTOR.services_by_name['ReadingService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _READER._serialized_start=41
  _READER._serialized_end=110
  _GETREADERSREQUEST._serialized_start=112
  _GETREADERSREQUEST._serialized_end=131
  _GETREADERSRESPONSE._serialized_start=133
  _GETREADERSRESPONSE._serialized_end=186
  _GETANSWERSREQUEST._serialized_start=188
  _GETANSWERSREQUEST._serialized_end=292
  _CONTEXTS._serialized_start=294
  _CONTEXTS._serialized_end=319
  _OFFSET._serialized_start=321
  _OFFSET._serialized_end=357
  _EVIDENCE._serialized_start=359
  _EVIDENCE._serialized_end=476
  _ANSWER._serialized_start=478
  _ANSWER._serialized_end=563
  _ANSWERSFORCONTEXT._serialized_start=565
  _ANSWERSFORCONTEXT._serialized_end=617
  _ANSWERSFORQUERY._serialized_start=619
  _ANSWERSFORQUERY._serialized_end=688
  _GETANSWERSRESPONSE._serialized_start=690
  _GETANSWERSRESPONSE._serialized_end=758
  _READINGSERVICE._serialized_start=761
  _READINGSERVICE._serialized_end=915
# @@protoc_insertion_point(module_scope)
