# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reader.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from . import pipelines_pb2 as pipelines__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creader.proto\x12\x06reader\x1a\x1cgoogle/protobuf/struct.proto\x1a\x0fpipelines.proto\"\x89\x01\n\x11GetAnswersRequest\x12%\n\x08pipeline\x18\x01 \x01(\x0b\x32\x13.pipelines.Pipeline\x12\x10\n\x08question\x18\x02 \x01(\t\x12\x10\n\x08passages\x18\x03 \x03(\t\x12)\n\x08metadata\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\"\xa6\x01\n\x06\x41nswer\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x19\n\x11start_char_offset\x18\x02 \x01(\r\x12\x17\n\x0f\x65nd_char_offset\x18\x03 \x01(\r\x12\x18\n\x10\x63onfidence_score\x18\x04 \x01(\x01\x12\x15\n\rpassage_index\x18\x05 \x01(\r\x12)\n\x08metadata\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct\"4\n\x11\x41nswersForPassage\x12\x1f\n\x07\x61nswers\x18\x01 \x03(\x0b\x32\x0e.reader.Answer\"@\n\x12GetAnswersResponse\x12*\n\x07\x61nswers\x18\x01 \x03(\x0b\x32\x19.reader.AnswersForPassage2M\n\x06Reader\x12\x43\n\nGetAnswers\x12\x19.reader.GetAnswersRequest\x1a\x1a.reader.GetAnswersResponseb\x06proto3')



_GETANSWERSREQUEST = DESCRIPTOR.message_types_by_name['GetAnswersRequest']
_ANSWER = DESCRIPTOR.message_types_by_name['Answer']
_ANSWERSFORPASSAGE = DESCRIPTOR.message_types_by_name['AnswersForPassage']
_GETANSWERSRESPONSE = DESCRIPTOR.message_types_by_name['GetAnswersResponse']
GetAnswersRequest = _reflection.GeneratedProtocolMessageType('GetAnswersRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETANSWERSREQUEST,
  '__module__' : 'reader_pb2'
  # @@protoc_insertion_point(class_scope:reader.GetAnswersRequest)
  })
_sym_db.RegisterMessage(GetAnswersRequest)

Answer = _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), {
  'DESCRIPTOR' : _ANSWER,
  '__module__' : 'reader_pb2'
  # @@protoc_insertion_point(class_scope:reader.Answer)
  })
_sym_db.RegisterMessage(Answer)

AnswersForPassage = _reflection.GeneratedProtocolMessageType('AnswersForPassage', (_message.Message,), {
  'DESCRIPTOR' : _ANSWERSFORPASSAGE,
  '__module__' : 'reader_pb2'
  # @@protoc_insertion_point(class_scope:reader.AnswersForPassage)
  })
_sym_db.RegisterMessage(AnswersForPassage)

GetAnswersResponse = _reflection.GeneratedProtocolMessageType('GetAnswersResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETANSWERSRESPONSE,
  '__module__' : 'reader_pb2'
  # @@protoc_insertion_point(class_scope:reader.GetAnswersResponse)
  })
_sym_db.RegisterMessage(GetAnswersResponse)

_READER = DESCRIPTOR.services_by_name['Reader']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETANSWERSREQUEST._serialized_start=72
  _GETANSWERSREQUEST._serialized_end=209
  _ANSWER._serialized_start=212
  _ANSWER._serialized_end=378
  _ANSWERSFORPASSAGE._serialized_start=380
  _ANSWERSFORPASSAGE._serialized_end=432
  _GETANSWERSRESPONSE._serialized_start=434
  _GETANSWERSRESPONSE._serialized_end=498
  _READER._serialized_start=500
  _READER._serialized_end=577
# @@protoc_insertion_point(module_scope)
