# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: retriever.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import parameter_pb2 as parameter__pb2
from . import indexer_pb2 as indexer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fretriever.proto\x12\x08retrieve\x1a\x0fparameter.proto\x1a\rindexer.proto\"T\n\x12RetrieverComponent\x12\x14\n\x0cretriever_id\x18\x01 \x01(\t\x12(\n\nparameters\x18\x02 \x03(\x0b\x32\x14.parameter.Parameter\"\x16\n\x14GetRetrieversRequest\"I\n\x15GetRetrieversResponse\x12\x30\n\nretrievers\x18\x01 \x03(\x0b\x32\x1c.retrieve.RetrieverComponent\"e\n\x0fRetrieveRequest\x12/\n\tretriever\x18\x01 \x01(\x0b\x32\x1c.retrieve.RetrieverComponent\x12\x10\n\x08index_id\x18\x02 \x01(\t\x12\x0f\n\x07queries\x18\x03 \x03(\t\"7\n\x03Hit\x12!\n\x08\x64ocument\x18\x01 \x01(\x0b\x32\x0f.index.Document\x12\r\n\x05score\x18\x02 \x01(\x01\"*\n\x0bHitPerQuery\x12\x1b\n\x04hits\x18\x01 \x03(\x0b\x32\r.retrieve.Hit\"7\n\x10RetrieveResponse\x12#\n\x04hits\x18\x01 \x03(\x0b\x32\x15.retrieve.HitPerQuery2\xa0\x01\n\tRetriever\x12P\n\rGetRetrievers\x12\x1e.retrieve.GetRetrieversRequest\x1a\x1f.retrieve.GetRetrieversResponse\x12\x41\n\x08Retrieve\x12\x19.retrieve.RetrieveRequest\x1a\x1a.retrieve.RetrieveResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retriever_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RETRIEVERCOMPONENT._serialized_start=61
  _RETRIEVERCOMPONENT._serialized_end=145
  _GETRETRIEVERSREQUEST._serialized_start=147
  _GETRETRIEVERSREQUEST._serialized_end=169
  _GETRETRIEVERSRESPONSE._serialized_start=171
  _GETRETRIEVERSRESPONSE._serialized_end=244
  _RETRIEVEREQUEST._serialized_start=246
  _RETRIEVEREQUEST._serialized_end=347
  _HIT._serialized_start=349
  _HIT._serialized_end=404
  _HITPERQUERY._serialized_start=406
  _HITPERQUERY._serialized_end=448
  _RETRIEVERESPONSE._serialized_start=450
  _RETRIEVERESPONSE._serialized_end=505
  _RETRIEVER._serialized_start=508
  _RETRIEVER._serialized_end=668
# @@protoc_insertion_point(module_scope)
